spring:
  application:
    name: internship-service
  config:
    import: "configserver:http://localhost:8888"
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka